apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:                # 所有的resource都會被打上這個Annotations
  note: Hello, I am production!
resources:                        # resources YAML的存放位置
- ../../base
patchesStrategicMerge:            # 要被讀取進來的新設定檔
- deployment.yaml
