apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
  namespace: nginx-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:q
      - name: the-container
        image: quay.io/jacky_lee_eds/nginx:1.27.4
