apiVersion: apps/v1
kind: Deployment
metadata:
  name: base
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      serviceAccount: admin
      containers:
      - name: base
        image: quay.io/jacky_lee_eds/nginx:1.27.4-1
