apiVersion: apps/v1
kind: Deployment
metadata:
  name: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: base
        image: quay.io/jacky_lee_eds/nginx:1.27.4-1
